name: Check data

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  stuff:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install DepotDownloader
      run: |
        wget https://github.com/SteamRE/DepotDownloader/releases/download/DepotDownloader_2.7.1/DepotDownloader-linux-x64.zip
        unzip DepotDownloader-linux-x64.zip
        chmod +x ./DepotDownloader

    - name: Fetch Deadlock pak index
      run: |
        ./DepotDownloader -app 1422450 -depot 1422456 -username ${{ secrets.STEAMWORKS_USER }} -password ${{ secrets.STEAMWORKS_PASSWORD }} -filelist filelist_pak01_dir.txt
        find ./depots -type f -exec mv -t . {} +

    - name: Install dependencies
      working-directory: ./kv3bs
      run: dotnet restore

    - name: Build
      working-directory: ./kv3bs
      run: dotnet build

    - name: Generate vpk list
      working-directory: ./kv3bs
      run: dotnet run list ../pak01_dir.vpk > ../vpks_filelist.txt

    - name: Download necessary vpks
      run: |
        ./DepotDownloader -app 1422450 -depot 1422456 -username ${{ secrets.STEAMWORKS_USER }} -password ${{ secrets.STEAMWORKS_PASSWORD }} -filelist vpks_filelist.txt
        find ./depots -type f -exec mv -t . {} +

    - name: Extract vdata
      working-directory: ./kv3bs
      run: dotnet run json ../pak01_dir.vpk

    - name: Organize
      run: |
        mkdir -p data
        cp ./kv3bs/*.vdata.json ./data/

    - name: Commit and push
      continue-on-error: true
      run: |
        git config --global user.name ouwou
        git config --global user.email "26526779+ouwou@users.noreply.github.com"
        git add data
        git commit -m "Automated update"
        git push
